services:
  webserver:
    image: nginx:1.25-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      